# JournalToExodus.jl   (targets Exodus.jl v0.14.4)
# ============================================================================
# Interprets a SUBSET of Cubit/Coreform journal syntax to build simple
# structured-hex geometries (cube, cantilever/beam) and write them to an
# ExodusII (.g/.e/.exo) file via Exodus.jl -- no Cubit required.
#
#   julia JournalToExodus.jl input.jou            # output -> export name or input.g
#   julia JournalToExodus.jl input.jou out.g      # explicit output name
#
# SUPPORTED
#   ${name = expr}                         APREPRO variable assignment
#   create brick x {..} y {..} z {..}      single centered box
#   volume ... size {..}                   uniform mesh size
#   mesh volume all                        (implicit)
#   move volume N x {..} y {..} z {..} [include_merged]   translate the box
#   block N volume N ; block N name "..."
#   nodeset N surface with <coord> <op> <val> ; nodeset N name "..."
#   sideset N surface with <coord> <op> <val> ; sideset N name "..."
#   set ... (ignored) ; export mesh "..." overwrite
#   delete volume ... ; compress ids       -- reset stage; next brick starts fresh
#
# Multi-stage journals: an `export mesh "..."` flushes the current stage to disk
# and resets state, so a single .jou can produce multiple .g files (each stage
# is an independent brick + block/sets + export).
#
#   <coord> = x_coord|y_coord|z_coord ;  <op> = < > <= >=
#
# SELECTION SEMANTICS (matches Cubit's "surface with ..."):
#   The predicate selects a real BOUNDARY face of the box. The boundary plane it
#   refers to is the domain extent: max coord for '>'/'>=', min coord for '<'/'<='.
#   A node/face qualifies only if it lies ON that extreme plane -- NOT merely if its
#   coordinate passes the comparison. (A raw centroid comparison wrongly grabs
#   interior faces; this plane test is the correct interpretation.) Predicates are
#   evaluated on the FINAL post-move coordinates, exactly as Cubit does.
#
# NOT supported (needs a geometry kernel): cylinders, webcut, imprint/merge,
# multiple volumes, booleans, tets.
#
# DISCLAIMER: This script was generated by claude as a replacement for calling
# cubit to generate cantilever meshes.
# ============================================================================

using Exodus

# ---- APREPRO-style expression evaluator -----------------------------------
# Substitute only variable-name symbols; leave operator/function heads (the
# first arg of a :call, e.g. :/ :+ :sqrt) untouched so they evaluate normally.
function eval_expr(expr::AbstractString, env::Dict{String,Float64})
    e = Meta.parse(strip(expr))
    walk_sym(x::Symbol) =
        haskey(env, String(x)) ? env[String(x)] :
        x === :pi ? Float64(pi) :
        error("unknown variable in expression: $x")
    function walk(x)
        if x isa Symbol
            return walk_sym(x)
        elseif x isa Expr
            if x.head === :call
                # args[1] is the operator/function; keep it, recurse on operands
                head = x.args[1]
                return Expr(:call, head, map(walk, x.args[2:end])...)
            else
                return Expr(x.head, map(walk, x.args)...)
            end
        else
            return x   # numeric literal
        end
    end
    return Float64(eval(walk(e)))
end

subst_braces(s, env) =
    replace(s, r"\{([^}]*)\}" => m -> string(eval_expr(m[2:end-1], env)))

const AXIS = Dict("x"=>1,"y"=>2,"z"=>3,"x_coord"=>1,"y_coord"=>2,"z_coord"=>3)

# Cubit surface numbering for an unmodified `create brick` (verified from the
# journal's own surface<->name pairing). Renumbering after webcut/merge would
# break this, but those operations aren't supported here anyway.
#   surface => (axis, sign)   axis: 1=x 2=y 3=z ; sign: +1 max plane, -1 min plane
const BRICK_SURFACE = Dict(
    1 => (3, +1),  # +z
    2 => (3, -1),  # -z
    3 => (2, -1),  # -y
    4 => (1, -1),  # -x
    5 => (2, +1),  # +y
    6 => (1, +1),  # +x
)

# ---- journal spec ----------------------------------------------------------
# A selector is one of:
#   (:coord, axis, op, val)   -> "surface with <coord> <op> <val>"
#   (:surface, sid)           -> "surface N"  (brick surface id)
#   (:all,)                   -> "volume all"
const Selector = Tuple

mutable struct Journal
    brick::Union{Nothing,NTuple{3,Float64}}
    hsize::Union{Nothing,Float64}
    translate::Vector{Float64}
    block_name::String
    nsets::Vector{Tuple{Int,Selector}}   # (set_id, selector)
    ssets::Vector{Tuple{Int,Selector}}
    nset_names::Dict{Int,String}
    sset_names::Dict{Int,String}
    export_name::String
end
Journal() = Journal(nothing, nothing, zeros(3), "block_1",
                    [], [], Dict{Int,String}(), Dict{Int,String}(), "")

op_symbol(s) = s == "<"  ? :lt : s == ">"  ? :gt :
               s == "<=" ? :le : s == ">=" ? :ge :
               error("unsupported operator: $s")

function parse_journal(path)
    env = Dict{String,Float64}(); J = Journal()
    stages = Tuple{Journal,String}[]   # (journal, export_name) in order encountered
    for raw in eachline(path)
        line = strip(raw)
        (isempty(line) || startswith(line, "#")) && continue
        m = match(r"^\$\{\s*(\w+)\s*=\s*(.+?)\s*\}$", line)
        if m !== nothing
            env[m.captures[1]] = eval_expr(m.captures[2], env); continue
        end
        line = subst_braces(line, env); toks = split(line); kw = lowercase(toks[1])

        if kw == "create" && lowercase(toks[2]) == "brick"
            d = Dict{String,Float64}()
            for ax in ("x","y","z")
                i = findfirst(==(ax), toks); i !== nothing && (d[ax] = parse(Float64, toks[i+1]))
            end
            J.brick = (d["x"], d["y"], d["z"])
        elseif kw == "volume" && any(==("size"), toks)
            J.hsize = parse(Float64, toks[findfirst(==("size"), toks)+1])
        elseif kw == "mesh"
            # implicit
        elseif kw == "move" && lowercase(toks[2]) == "volume"
            i = 3
            while i <= length(toks)
                t = lowercase(toks[i])
                if t in ("x","y","z")
                    J.translate[AXIS[t]] += parse(Float64, toks[i+1]); i += 2
                else
                    i += 1
                end
            end
        elseif kw == "block"
            any(==("name"), toks) && (J.block_name = match(r"\"(.*?)\"", line).captures[1])
        elseif kw in ("nodeset","sideset")
            sid = parse(Int, toks[2])
            target = kw == "nodeset" ? J.nsets : J.ssets
            if any(==("name"), toks)
                nm = match(r"\"(.*?)\"", line).captures[1]
                (kw == "nodeset" ? J.nset_names : J.sset_names)[sid] = nm
            elseif any(==("with"), toks)
                wi = findfirst(==("with"), toks)
                sel = (:coord, AXIS[lowercase(toks[wi+1])], op_symbol(toks[wi+2]),
                       parse(Float64, toks[wi+3]))
                push!(target, (sid, sel))
            elseif any(==("surface"), toks)
                si = findfirst(==("surface"), toks)
                arg = lowercase(toks[si+1])
                if arg == "all"
                    push!(target, (sid, (:all,)))
                else
                    push!(target, (sid, (:surface, parse(Int, arg))))
                end
            elseif any(==("volume"), toks)
                # e.g. "nodeset 7 volume all"
                push!(target, (sid, (:all,)))
            end
        elseif kw == "export"
            mm = match(r"\"(.*?)\"", line); mm !== nothing && (J.export_name = mm.captures[1])
            # `export` flushes the current stage to disk; start fresh so the next
            # `create brick` doesn't inherit block name / nsets / translation.
            push!(stages, (J, J.export_name))
            J = Journal()
        elseif kw == "delete" && length(toks) >= 2 && lowercase(toks[2]) == "volume"
            # `delete volume ...` drops the geometry; if we haven't already
            # flushed via `export`, discard the in-progress stage.
            J = Journal()
        elseif kw == "compress"
            # `compress ids` -- no-op for us (we don't carry Cubit id state)
        elseif kw == "set"
            # ignore
        else
            @warn "ignoring unsupported journal line: $line"
        end
    end
    # Trailing state with no `export` -- keep it so the CLI can still pick an
    # output name (matches the single-stage behavior of the original script).
    if J.brick !== nothing || !isempty(J.nsets) || !isempty(J.ssets) || isempty(stages)
        push!(stages, (J, J.export_name))
    end
    return stages
end

# ---- mesh build + Exodus write (0.14.4 API) --------------------------------
function write_exodus(J::Journal, outfile)
    J.brick === nothing && error("journal has no `create brick`")
    J.hsize === nothing && error("journal has no `volume ... size`")

    lx, ly, lz = J.brick
    # Cubit's mesher picks the number of intervals that makes the element size
    # no COARSER than requested -- i.e. ceil(L/h), not round. (A round() here
    # under-refines any axis whose L/h has a fractional part < 0.5, e.g. a
    # thickness of 1.5*h becomes 1 element instead of 2, halving the through
    # -thickness resolution.) The small epsilon keeps exact ratios (L/h == 2.0)
    # from spuriously bumping up to 3.
    ndiv(L) = max(1, ceil(Int, L/J.hsize - 1e-9))
    nx = ndiv(lx); ny = ndiv(ly); nz = ndiv(lz)
    nnx, nny, nnz = nx+1, ny+1, nz+1
    xs = range(-lx/2, lx/2; length=nnx) .+ J.translate[1]
    ys = range(-ly/2, ly/2; length=nny) .+ J.translate[2]
    zs = range(-lz/2, lz/2; length=nnz) .+ J.translate[3]
    nid(i,j,k) = (k-1)*nnx*nny + (j-1)*nnx + (i-1) + 1

    num_nodes = nnx*nny*nnz
    coords = Matrix{Float64}(undef, 3, num_nodes)   # 3 x num_nodes
    for k in 1:nnz, j in 1:nny, i in 1:nnx
        p = nid(i,j,k); coords[1,p]=xs[i]; coords[2,p]=ys[j]; coords[3,p]=zs[k]
    end

    num_elem = nx*ny*nz
    conn = Matrix{Int32}(undef, 8, num_elem)        # 0.14.4: 8 x num_elem matrix
    e = 0
    for k in 1:nz, j in 1:ny, i in 1:nx
        e += 1
        conn[1,e]=nid(i  ,j  ,k  ); conn[2,e]=nid(i+1,j  ,k  )
        conn[3,e]=nid(i+1,j+1,k  ); conn[4,e]=nid(i  ,j+1,k  )
        conn[5,e]=nid(i  ,j  ,k+1); conn[6,e]=nid(i+1,j  ,k+1)
        conn[7,e]=nid(i+1,j+1,k+1); conn[8,e]=nid(i  ,j+1,k+1)
    end

    gmin = (minimum(xs), minimum(ys), minimum(zs))
    gmax = (maximum(xs), maximum(ys), maximum(zs))
    tol = 1e-6

    # plane a coordinate predicate points at, with a validity check
    function coord_plane(ax, op, val)
        plane = (op in (:gt,:ge)) ? gmax[ax] : gmin[ax]
        ok = op === :lt ? plane <  val :
             op === :le ? plane <= val :
             op === :gt ? plane >  val :
                          plane >= val
        return plane, ok
    end

    # resolve any selector to (axis, plane) for a boundary face, or :all / :none
    function resolve(sel)
        if sel[1] === :coord
            _, ax, op, val = sel
            plane, ok = coord_plane(ax, op, val)
            ok ? (ax, plane) : :none
        elseif sel[1] === :surface
            sid = sel[2]
            haskey(BRICK_SURFACE, sid) || (@warn "unknown brick surface id $sid"; return :none)
            ax, sgn = BRICK_SURFACE[sid]
            (ax, sgn > 0 ? gmax[ax] : gmin[ax])
        elseif sel[1] === :all
            :all
        else
            :none
        end
    end

    function node_ids(sel)
        r = resolve(sel)
        r === :all  && return Int32.(1:num_nodes)
        r === :none && (@warn "selector $sel matched nothing; empty nodeset"; return Int32[])
        ax, plane = r
        Int32[ p for p in 1:num_nodes if abs(coords[ax,p]-plane) < tol ]
    end

    local_faces = ((1,2,6,5),(2,3,7,6),(3,4,8,7),(4,1,5,8),(1,4,3,2),(5,6,7,8))
    function side_data(sel)
        r = resolve(sel)
        els = Int32[]; sds = Int32[]; nnps = Int32[]; snodes = Int32[]
        if r === :all
            @warn "sideset selector `all` is ambiguous; skipping (use coord/surface)"
            return els, sds, nnps, snodes
        elseif r === :none
            @warn "selector $sel matched nothing; empty sideset"
            return els, sds, nnps, snodes
        end
        ax, plane = r
        for elem in 1:num_elem, (f, ln) in enumerate(local_faces)
            ids = (conn[ln[1],elem], conn[ln[2],elem], conn[ln[3],elem], conn[ln[4],elem])
            if all(abs(coords[ax, id]-plane) < tol for id in ids)
                push!(els, elem); push!(sds, f); push!(nnps, Int32(4))
                append!(snodes, ids)
            end
        end
        els, sds, nnps, snodes
    end

    init = Initialization(Int32(3), Int32(num_nodes), Int32(num_elem),
                          Int32(1), Int32(length(J.nsets)), Int32(length(J.ssets)))

    isfile(outfile) && rm(outfile)
    exo = ExodusDatabase{Int32,Int32,Int32,Float64}(outfile, "w", init)

    write_coordinates(exo, coords)

    # blocks have their own writer (NOT write_sets, which only handles
    # node/side sets in 0.14.4). write_blocks chains params + connectivity.
    block = Block(Int32(1), num_elem, 8, "HEX8", conn)
    write_blocks(exo, [block])
    write_names(exo, Block, [J.block_name])

    if !isempty(J.nsets)
        ns = [ NodeSet(Int32(sid), node_ids(sel)) for (sid, sel) in J.nsets ]
        write_sets(exo, ns)
        write_names(exo, NodeSet, [get(J.nset_names, s[1], "nodeset_$(s[1])") for s in J.nsets])
    end

    if !isempty(J.ssets)
        ss = SideSet[]
        for (sid, sel) in J.ssets
            els,sds,nnps,snodes = side_data(sel)
            push!(ss, SideSet(Int32(sid), els, sds, nnps, snodes))
        end
        write_sets(exo, ss)
        write_names(exo, SideSet, [get(J.sset_names, s[1], "sideset_$(s[1])") for s in J.ssets])
    end

    close(exo)

    println("Wrote $outfile")
    println("  box $(lx)x$(ly)x$(lz), size $(J.hsize) -> $(nx)x$(ny)x$(nz) grid, translate $(J.translate)")
    println("  $num_nodes nodes, $num_elem hex8, block \"$(J.block_name)\", ",
            "$(length(J.nsets)) nodesets, $(length(J.ssets)) sidesets")
    return outfile
end

function journal_to_exodus(jou, out="")
    stages = parse_journal(jou)
    outputs = String[]
    if length(stages) == 1
        J, name = stages[1]
        fname = !isempty(out)  ? out  :
                !isempty(name) ? name :
                replace(jou, r"\.jou$"=>"") * ".g"
        write_exodus(J, fname); push!(outputs, fname)
    else
        # Multi-stage: the CLI `out` name is ambiguous, so require every stage
        # to carry its own `export mesh "..."` in the journal.
        !isempty(out) && @warn "ignoring output override `$out`: journal has $(length(stages)) stages; using per-stage export names"
        for (i, (J, name)) in enumerate(stages)
            isempty(name) && error("stage $i has no `export mesh \"...\"` -- required when a journal has multiple stages")
            write_exodus(J, name); push!(outputs, name)
        end
    end
    return outputs
end

if abspath(PROGRAM_FILE) == @__FILE__
    length(ARGS) < 1 && error("usage: julia JournalToExodus.jl input.jou [output.g]")
    journal_to_exodus(ARGS[1], length(ARGS) >= 2 ? ARGS[2] : "")
end